### PR TITLE
this is my 2nd commit by sravani through branch

### PR DESCRIPTION
**Pull request by sravanigogula19**
hi team lead  ,
i have made changes in the code please check this

### CODE REVIEW

**Comment by sravanigogula** [comment]
hi sravni
please some make changes in the code

**Comment by sravanigogula19** [comment]
hi TL,
make some changes aaccordingly

**Comment by sravanigogula19** [comment]
hichanges done in my 3rd commit

**Comment by sravanigogula19** [comment]
hi tl. 
changes done in my 3rd commit

**Comment by sravanigogula** [comment]
hi sravani,
reviwed ur code

**Comment by sravanigogula19** [comment]
ok tl , 
thankyou

**Pull request merged**
